CREATE TABLE ReasonAdmission (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(25) NOT NULL,
    Code VARCHAR(10) NOT NULL,
    Status VARCHAR(10) NOT NULL CHECK (Status IN ('INGRESO', 'EGRESO')),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Workers (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CI VARCHAR(10) NOT NULL,
    Name VARCHAR(25) NOT NULL,
    DateAdmission DATE NOT NULL,
    Value DECIMAL(10, 2) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    CONSTRAINT CHK_CI CHECK (LEN(CI) = 10)
);

CREATE TABLE PayrollHeader (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    WorkerId INT NOT NULL,
    Description VARCHAR(255) NOT NULL,
    DatePayroll DATE NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_Workers FOREIGN KEY (WorkerId) REFERENCES Workers(Id)
);

CREATE TABLE PayrollDetail (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ReasonId INT NOT NULL,
    PayrollId INT NOT NULL,
    Price DECIMAL(10, 2),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_Reason FOREIGN KEY (ReasonId) REFERENCES ReasonAdmission(Id),
    CONSTRAINT FK_Payroll FOREIGN KEY (PayrollId) REFERENCES PayrollHeader(Id)
);
